#!/usr/bin/env python3
"""Emit journal-named display files and verify the manifest, disk and manuscript agree.

Repository figures are named for the analysis that produced them
(`aim3_human_compiled.png`); a journal wants them named for where they appear
(`Figure_1.png`). Keeping both, with `config/displays.yaml` as the single source of
truth, means a reviewer can trace any submitted display back to the script that made
it, and nobody has to rename files by hand at submission time.

Three checks run every time, and any failure exits non-zero:

  1. every display in the manifest has its source file on disk
  2. every figure on disk is accounted for -- either submitted or explicitly listed
     as generated-but-not-submitted, so unused files cannot accumulate unnoticed
  3. every manifest label appears in the manuscript, and every manuscript label
     appears in the manifest

Output goes to `reports/submission/`, which is rebuilt from scratch on each run.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.config import CONFIG_DIR, FIGURES_DIR, REPORTS_DIR  # noqa: E402

MANIFEST = CONFIG_DIR / "displays.yaml"
OUT_DIR = REPORTS_DIR / "submission"
MANUSCRIPT = REPO_ROOT / "publication" / "Naeem_final_clean_cardiac_CT_readability.docx"


def slug(label: str) -> str:
    """'eFigure 7' -> 'eFigure_7'. Journals want no spaces in submitted filenames."""
    return label.replace(" ", "_")


def manuscript_labels() -> set[str] | None:
    """Display labels the manuscript actually defines, or None if it is unavailable."""
    if not MANUSCRIPT.exists():
        return None
    try:
        import docx

        from src.manuscript import paragraph_texts
    except ImportError:
        return None
    found = set()
    for para in paragraph_texts(docx.Document(str(MANUSCRIPT))):
        m = re.match(r"^(e?(?:Table|Figure) \d+)(?:\s*\([^)]*\))?\.\s+\S", para.strip())
        if m:
            found.add(m.group(1))
    return found


def main() -> int:
    manifest = yaml.safe_load(MANIFEST.read_text())
    figures = manifest["main_figures"] + manifest["supplementary_figures"]
    tables = manifest["main_tables"] + manifest["supplementary_tables"]
    problems: list[str] = []

    # 1. sources exist
    for item in figures:
        if not (FIGURES_DIR / item["source"]).exists():
            problems.append(f"{item['label']}: source missing ({item['source']})")
    for item in tables:
        if not (REPO_ROOT / item["source_report"]).exists():
            problems.append(f"{item['label']}: report missing ({item['source_report']})")

    # 2. nothing on disk is unaccounted for
    submitted = {i["source"] for i in figures}
    known_unused = {i["source"] for i in manifest.get("generated_but_not_submitted", [])}
    on_disk = {p.name for p in FIGURES_DIR.glob("*.png")}
    for orphan in sorted(on_disk - submitted - known_unused):
        problems.append(
            f"{orphan}: on disk but neither submitted nor listed as intentionally unused")
    for missing in sorted((submitted | known_unused) - on_disk):
        problems.append(f"{missing}: named in the manifest but not on disk")

    # 3. manifest and manuscript agree
    ms = manuscript_labels()
    if ms is not None:
        declared = {i["label"] for i in figures + tables}
        for label in sorted(declared - ms):
            problems.append(f"{label}: in the manifest but has no legend in the manuscript")
        for label in sorted(ms - declared):
            problems.append(f"{label}: has a legend in the manuscript but is not in the manifest")

    # emit journal-named copies
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)
    for item in figures:
        src = FIGURES_DIR / item["source"]
        if src.exists():
            shutil.copy2(src, OUT_DIR / f"{slug(item['label'])}.png")

    lines = ["# Submitted displays", ""]
    for group, heading in (("main_figures", "Main figures"),
                           ("main_tables", "Main tables"),
                           ("supplementary_figures", "Supplementary figures"),
                           ("supplementary_tables", "Supplementary tables")):
        lines += [f"## {heading}", ""]
        for item in manifest[group]:
            origin = item.get("source") or item["source_report"]
            lines.append(f"- **{item['label']}.** {' '.join(item['title'].split())}  ")
            lines.append(f"  generated by `{item['script']}` from `{origin}`")
        lines.append("")
    (OUT_DIR / "README.md").write_text("\n".join(lines))

    n_main = len(manifest["main_figures"]) + len(manifest["main_tables"])
    print("=" * 74)
    print("SUBMISSION DISPLAYS")
    print("=" * 74)
    print(f"  main displays      : {n_main}  (journal limit for this article type: 5)")
    print(f"  supplementary      : {len(manifest['supplementary_figures'])} figures, "
          f"{len(manifest['supplementary_tables'])} tables")
    print(f"  written to         : {OUT_DIR.relative_to(REPO_ROOT)}")
    if n_main > 5:
        problems.append(f"{n_main} main displays exceeds the limit of 5")
    if problems:
        print(f"\n  {len(problems)} PROBLEM(S):")
        for p in problems:
            print(f"    - {p}")
        return 1
    print("\n  manifest, figures on disk and manuscript all agree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
